{
 "title": "ShardingSphere Proxy Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "shardingsphere",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{kubernetes_namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "interval",
    "query": "1m, 2m, 5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Kubernetes General Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Replicas",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"$shardingsphere\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Pods Runing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_status_phase{phase=\"Running\",kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(rate(container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"$shardingsphere.*\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",container=\"shardingsphere-proxy\",namespace=\"$namespace\"}) by (pod_name))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Pod network IO",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{kubernetes_namespace=\"$namespace\",pod_name=~\"$shardingsphere.*\"}[$interval]) ))",
     "legendFormat": "接收"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{kubernetes_namespace=\"$namespace\",pod_name=~\"$shardingsphere.*\"}[$interval]) ))",
     "legendFormat": "发送"
    }
   ]
  },
  { "title": "ShardingSphere Proxy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "JVM 已用内存",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\",area=\"heap\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": "jvm_memory_bytes_used{kubernetes_namespace=\"$namespace\",area=\"nonheap\"}",
     "legendFormat": "已用非堆内存"
    }
   ]
  },
  {
   "title": "GC 时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM 类加载",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Proxy 连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "proxy_connection_total{kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(proxy_request_total{kubernetes_namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "执行耗时热力图",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "ceil(increase(proxy_execute_latency_millis_bucket{kubernetes_namespace=\"$namespace\", le!=\"+Inf\"}[$interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Proxy 执行异常数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(proxy_execute_error_total{kubernetes_namespace=\"$namespace\"}[$interval]))"
    }
   ]
  },
  {
   "title": "SQL 路由数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(route_sql_insert_total{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$shardingsphere.*\"}[$interval]))",
     "legendFormat": "Insert"
    },
    {
     "expr": "sum(rate(route_sql_select_total{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$shardingsphere.*\"}[$interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(route_sql_update_total{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$shardingsphere.*\"}[$interval]))",
     "legendFormat": "update"
    },
    {
     "expr": "sum(rate(route_sql_delete_total{kubernetes_namespace=\"$namespace\",kubernetes_pod_name=~\"$shardingsphere.*\"}[$interval]))",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum(meta_data_info{name=\"database_count\",kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$shardingsphere.*\"}) / count(meta_data_info{name=\"database_count\",kubernetes_namespace=\"$namespace\", kubernetes_pod_name=~\"$shardingsphere.*\"}))",
     "legendFormat": "逻辑库数量"
    }
   ]
  }
 ]
}