{
 "title": "ShardingSphere-Operator Runtime dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Reconcile Total [Contorller=shardingsphereproxy][Last 5min]",
   "type": "timeseries",
   "description": "Total number of reconciliation.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{app=\"shardingsphere-operator\", controller=\"shardingsphereproxy\"}[5m])) by (instance, controller, result)",
     "legendFormat": "{{ instance }}-{{ result}}"
    }
   ]
  },
  {
   "title": "Reconcile Total [Contorller=shardingsphereproxyserverconfig][Last 5min]",
   "type": "timeseries",
   "description": "Total number of reconciliation.",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{app=\"shardingsphere-operator\", controller=\"shardingsphereproxyserverconfig\"}[5m])) by (instance, controller, result)",
     "legendFormat": "{{ instance }}-{{ result}}"
    }
   ]
  },
  {
   "title": "Seconds for item stays in workqueue (P50)",
   "type": "timeseries",
   "description": "Seconds an item stays in workqueue before being requested.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{app=\"shardingsphere-operator\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Seconds processing item from workqueue [P50]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{app=\"shardingsphere-operator\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{ instance }}-{{ name }}"
    }
   ]
  },
  {
   "title": "Reconcile Errors Total [Last 5min]",
   "type": "timeseries",
   "description": "Total number of reconciliation errors.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{app=\"shardingsphere-operator\"}[5m])) by (instance, controller)",
     "legendFormat": "{{ instance }}-{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Time Buckets [Controller=shardingsphereproxy]",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{app=\"shardingsphere-operator\", controller=\"shardingsphereproxy\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Reconcile Time Buckets [Controller=shardingsphereproxyserverconfig]",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{app=\"shardingsphere-operator\", controller=\"shardingsphereproxyserverconfig\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}