// Code generated by MockGen. DO NOT EDIT.
// Source: agent-server.go

// Package mock_pkg is a generated GoMock package.
package mock_pkg

import (
	reflect "reflect"

	model "github.com/apache/shardingsphere-on-cloud/pitr/cli/internal/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIAgentServer is a mock of IAgentServer interface.
type MockIAgentServer struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentServerMockRecorder
}

// MockIAgentServerMockRecorder is the mock recorder for MockIAgentServer.
type MockIAgentServerMockRecorder struct {
	mock *MockIAgentServer
}

// NewMockIAgentServer creates a new mock instance.
func NewMockIAgentServer(ctrl *gomock.Controller) *MockIAgentServer {
	mock := &MockIAgentServer{ctrl: ctrl}
	mock.recorder = &MockIAgentServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentServer) EXPECT() *MockIAgentServerMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockIAgentServer) Backup(in *model.BackupIn) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockIAgentServerMockRecorder) Backup(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockIAgentServer)(nil).Backup), in)
}

// CheckStatus mocks base method.
func (m *MockIAgentServer) CheckStatus() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockIAgentServerMockRecorder) CheckStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockIAgentServer)(nil).CheckStatus))
}

// DeleteBackup mocks base method.
func (m *MockIAgentServer) DeleteBackup(in *model.DeleteBackupIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBackup", in)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBackup indicates an expected call of DeleteBackup.
func (mr *MockIAgentServerMockRecorder) DeleteBackup(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBackup", reflect.TypeOf((*MockIAgentServer)(nil).DeleteBackup), in)
}

// Restore mocks base method.
func (m *MockIAgentServer) Restore(in *model.RestoreIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockIAgentServerMockRecorder) Restore(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockIAgentServer)(nil).Restore), in)
}

// ShowDetail mocks base method.
func (m *MockIAgentServer) ShowDetail(in *model.ShowDetailIn) (*model.BackupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowDetail", in)
	ret0, _ := ret[0].(*model.BackupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowDetail indicates an expected call of ShowDetail.
func (mr *MockIAgentServerMockRecorder) ShowDetail(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDetail", reflect.TypeOf((*MockIAgentServer)(nil).ShowDetail), in)
}

// ShowDiskSpace mocks base method.
func (m *MockIAgentServer) ShowDiskSpace(in *model.DiskSpaceIn) (*model.DiskSpaceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowDiskSpace", in)
	ret0, _ := ret[0].(*model.DiskSpaceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowDiskSpace indicates an expected call of ShowDiskSpace.
func (mr *MockIAgentServerMockRecorder) ShowDiskSpace(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDiskSpace", reflect.TypeOf((*MockIAgentServer)(nil).ShowDiskSpace), in)
}

// ShowList mocks base method.
func (m *MockIAgentServer) ShowList(in *model.ShowListIn) ([]model.BackupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowList", in)
	ret0, _ := ret[0].([]model.BackupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowList indicates an expected call of ShowList.
func (mr *MockIAgentServerMockRecorder) ShowList(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowList", reflect.TypeOf((*MockIAgentServer)(nil).ShowList), in)
}
