/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: agent-server.go

// Package mock_pkg is a generated GoMock package.
package mock_pkg

import (
	reflect "reflect"

	model "github.com/apache/shardingsphere-on-cloud/pitr/cli/internal/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIAgentServer is a mock of IAgentServer interface.
type MockIAgentServer struct {
	ctrl     *gomock.Controller
	recorder *MockIAgentServerMockRecorder
}

// MockIAgentServerMockRecorder is the mock recorder for MockIAgentServer.
type MockIAgentServerMockRecorder struct {
	mock *MockIAgentServer
}

// NewMockIAgentServer creates a new mock instance.
func NewMockIAgentServer(ctrl *gomock.Controller) *MockIAgentServer {
	mock := &MockIAgentServer{ctrl: ctrl}
	mock.recorder = &MockIAgentServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAgentServer) EXPECT() *MockIAgentServerMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockIAgentServer) Backup(in *model.BackupIn) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockIAgentServerMockRecorder) Backup(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockIAgentServer)(nil).Backup), in)
}

// CheckStatus mocks base method.
func (m *MockIAgentServer) CheckStatus() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckStatus")
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckStatus indicates an expected call of CheckStatus.
func (mr *MockIAgentServerMockRecorder) CheckStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckStatus", reflect.TypeOf((*MockIAgentServer)(nil).CheckStatus))
}

// Restore mocks base method.
func (m *MockIAgentServer) Restore(in *model.RestoreIn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Restore indicates an expected call of Restore.
func (mr *MockIAgentServerMockRecorder) Restore(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockIAgentServer)(nil).Restore), in)
}

// ShowDetail mocks base method.
func (m *MockIAgentServer) ShowDetail(in *model.ShowDetailIn) (*model.BackupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowDetail", in)
	ret0, _ := ret[0].(*model.BackupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowDetail indicates an expected call of ShowDetail.
func (mr *MockIAgentServerMockRecorder) ShowDetail(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowDetail", reflect.TypeOf((*MockIAgentServer)(nil).ShowDetail), in)
}

// ShowList mocks base method.
func (m *MockIAgentServer) ShowList(in *model.ShowListIn) ([]model.BackupInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowList", in)
	ret0, _ := ret[0].([]model.BackupInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShowList indicates an expected call of ShowList.
func (mr *MockIAgentServerMockRecorder) ShowList(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowList", reflect.TypeOf((*MockIAgentServer)(nil).ShowList), in)
}
